eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  sleuth:
    sampler:
      rate: 1
  zipkin:
    base-url: http://10.10.253.11:9411/