eureka:
  instance:
    hostname: "eureka"
  environment: "dev"
  datacenter: "dev"
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka